all : iobound cpubound part1 part2 part3 part4 part5


iobound.o: iobound.c
	gcc -c iobound.c

cpubound.o: cpubound.c
		gcc -c cpubound.c

part1.o: part1.c
		gcc -c part1.c

part2.o: part2.c
		gcc -c part2.c

part3.o: part3.c
		gcc -c part3.c

part4.o: part4.c
		gcc -c part4.c

part5.o: part5.c
		gcc -c part5.c

clean:
	rm -f core *.o iobound
	rm -f core *.o cpubound
	rm -f core *.o part1
	rm -f core *.o part2
	rm -f core *.o part3
	rm -f core *.o part4
	rm -f core *.o part5
